config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get '/bookings/profile', to: 'bookings#profile', as: 'profile'
  get '/dresses/favorites', to: 'dresses#favorites', as: 'favorites'
  get 'dresses/listings', to: 'dresses#listings', as: 'listings'
  resources :dresses do
    resources :bookings, only: %i[new create]
    resources :reviews, only: :create
  end
  resources :bookings, only: %i[destroy index update]
  resources :reviews, only: [:destroy]
  get '/dresses/:id/favorite', to: 'dresses#favorite', as: 'favorite'
  resources :articles
end

app/views/shared/_carousel.html.erb
<div class="swiper-container-rtl pt-5">
  <div class="swiper mySwiper", id="swiper_p">
    <div class="swiper-wrapper">
      <% if @dress.photos.attached? %>
        <% @dress.photos.each do |photo| %>
          <div class="swiper-slide carousel-dress-card text-center mb-3">
            <%= cl_image_tag photo.key %>
          </div>
        <% end %>
      <% elsif @dress.dress_url.present? %>
        <div class="swiper-slide carousel-dress-card text-center mb-3">
          <%= image_tag(@dress.dress_url) %>
        </div>
      <% else %>
        <div class="swiper-slide carousel-dress-card text-center mb-3">
          <%= image_tag("bridal_gown_silhouette.png") %>
        </div>
      <% end %>
    </div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
    <div class="swiper-pagination"></div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center text-lg-start bg-light text-muted mt-5">
  <section
    class="d-flex justify-content-center p-4 border-bottom"
  >

    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
    </div>
  </section>

  <section class="">
    <div class="container text-center text-md-start mt-5">
      <div class="row mt-3">
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            2Bridal
          </h6>
          <p>
            Here to help you find the most amazing dress for your perfect day at prices you can afford.
          </p>
        </div>

        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            Links
          </h6>
          <p>
            <a href="#!" class="text-reset">Your Page</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Browse Dresses</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>

        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            Contact
          </h6>
          <p><i class="fas fa-home me-3"></i> 2 Chome-11-3 Meguro, Meguro City, Tokyo 153-0063 </p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@two-bridal.com
          </p>
          <p><i class="fas fa-phone me-3 pb-3"></i> 080-1111-2222</p>
        </div>
      </div>
    </div>
  </section>

  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2022 Copyright:
    <a class="text-reset fw-bold" href="">Team Chirpy</a>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to dresses_path, class: "navbar-brand", id: "nav" do %>
      <%= image_tag('wedding_dress.png') %>
        2Bridal
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <div class="d-flex">
          <div class="form-inline">
              <%= form_with url: dresses_path, method: :get, html: { class: 'mr-3', data: { refresh_list_target: 'form' } } do |f| %>
                <%= f.text_field :query,
                                  class: "search-bar form-control",
                                  placeholder: "Search All Dresses",
                                  value: params[:query],
                                  data: {
                                    refresh_list_target: 'searchInput',
                                    action: "keyup->refresh-list#update"
                                  } %>
              <% end %>
          </div>
        </div>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= current_user.avatar.attached? ? cl_image_tag(current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) :
            image_tag('users.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Your Listings", listings_path, class: "dropdown-item" %>
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Your Favorites", favorites_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login/Sign up", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>