config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get '/bookings/profile', to: 'bookings#profile', as: 'profile'
  get '/dresses/favorites', to: 'dresses#favorites', as: 'favorites'
  get 'dresses/listings', to: 'dresses#listings', as: 'listings'
  resources :dresses do
    resources :bookings, only: %i[new create]
    resources :reviews, only: :create
  end
  resources :bookings, only: %i[destroy index update]
  resources :reviews, only: [:destroy]
  get '/dresses/:id/favorite', to: 'dresses#favorite', as: 'favorite'
  resources :articles
end

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= image_path 'bride.jpg' %>')">
  <div class="container">
    <div class="m-5 text-center text-dark px-5 py-3">
      <h1>Here to help you find the dress you deserve for your perfect day</h1>
      <p>Start your search here.</p>
      <%= link_to "Browse Dresses", dresses_path, class: "btn btn-light" %>
    </div>
  </div>
</div>

<div class="container">
  <div class="m-5 text-center bg-light text-dark px-5 py-3">
    <h3>Experience the Magic of 2Bridal</h3>
    <p>We have the largest selection of rental dresses avaliable online. Ready for you to wear so your special day can be perfect.</p>
  </div>

  <div class="m-5 text-center bg-light text-dark px-5 py-5">
    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card home-card">
          <img src="https://www.kleinfeldbridal.com/wp-content/uploads/2021/08/ajp-386-scaled.jpg" class="card-img-top" alt="Wedding Dress Photo">
          <div class="card-body">
            <h5 class="card-title">Designs</h5>
            <p class="card-text">Hundreds of designers to choose from. From Monique Lhullier to Claire Pettibone and everything inbetween.</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card home-card">
          <img src="https://www.kleinfeldbridal.com/wp-content/uploads/2021/08/ajp-52-scaled.jpg" class="card-img-top" alt="Wedding Dress Photo">
          <div class="card-body">
            <h5 class="card-title">Sizes</h5>
            <p class="card-text">We have every size you could imagine available, no matter how big or small.</p>
          </div>
        </div>
      </div>
      <div class="col mb-4 d-flex align-items-stretch">
        <div class="card home-card">
          <img src="https://www.kleinfeldbridal.com/wp-content/uploads/2021/08/ajp-239-scaled.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Styles</h5>
            <p class="card-text">No matter where you are, we have a style to suit your special day because of our amazing providers from around the globe.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="m-5 text-center bg-light text-dark px-5 py-3" style="width:">
    <h3>About Us</h3>
    <p>Formed in 2022 as the result of a group project, 4 highly motivated students passionate about love decided to embark on what has become 2Bridal.</p>
    <button type="button" class="btn btn-outline-secondary">Check our blog for more</button>
  </div>

</div>

app/views/pages/listings.html.erb
<div class="container">
  <h2 class="my-3">Your Listings</h2>
  <h3>
    <% if @dresses.count == 0 %>
      No listings yet!
      <%= link_to 'Add a new dress?', new_dress_path, class: 'card-link' %>
    <% end %>
  </h3>
  <%# <% @dresses.count > 1 ? @dresses.count dresses :
     @dresses.count dress %>
  <div class="row justify-content-center">
    <% @dresses.each do |dress| %>
    <div class="dress-card text-center mb-3 listings">
      <%= link_to dress_path(dress) do %>
        <% if dress.photos.attached? %>
          <%= cl_image_tag(dress.photos.first.key) %>
        <% elsif dress.dress_url.present? %>
          <%= image_tag(dress.dress_url) %>
        <% else %>
          <%= image_tag("bridal_gown_silhouette.png") %>
        <% end %>
      <% end %>
      <p><%= dress.description %></p>
      <p><%= number_to_currency(dress.price_per_day, {unit: '¥', precision: 0}) %> per day</p>
      <div class="edit-dress">
        <%= link_to "Delete", dress_path(dress), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-secondary mb-5 mx-1" %>
        <%= link_to "Edit", edit_dress_path(dress), class: "btn btn-outline-secondary mb-5 mx-1" %>
      </div>
    </div>
    <% end %>
  </div>
  <%= link_to 'Add a New Dress', new_dress_path, class: 'btn btn-outline-secondary float-right' %>
</div>