config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get '/bookings/profile', to: 'bookings#profile', as: 'profile'
  get '/dresses/favorites', to: 'dresses#favorites', as: 'favorites'
  get 'dresses/listings', to: 'dresses#listings', as: 'listings'
  resources :dresses do
    resources :bookings, only: %i[new create]
    resources :reviews, only: :create
  end
  resources :bookings, only: %i[destroy index update]
  resources :reviews, only: [:destroy]
  get '/dresses/:id/favorite', to: 'dresses#favorite', as: 'favorite'
  resources :articles
end

app/controllers/dresses_controller.rb
class DressesController < ApplicationController
  before_action :set_dress, only: %i[show edit update destroy favorite]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @query = params[:query]
    @dresses = policy_scope(Dress).order(created_at: :desc)
    if params[:query].present?
      @dresses = Dress.search_dresses(params[:query])
    else
      @dresses = Dress.all
    end
    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'list.html', locals: { dresses: @dresses } }
    end
  end

  def show
    authorize @dress
    @booking = Booking.new
    @review = Review.new
  end

  def new
    @dress = Dress.new
    authorize @dress
  end

  def create
    @dress = Dress.new(dress_params)
    authorize @dress
    @dress.user = current_user
    if @dress.save
      redirect_to listings_path
    else
      render :new
    end
  end

  def edit
    authorize @dress
  end

  def update
    authorize @dress
    @dress.update(dress_params)
    @dress.user = current_user
    if @dress.save
      redirect_to dress_path(@dress)
    else
      render :edit
    end
  end

  def destroy
    authorize @dress
    @dress.destroy
    flash[:remove] = "Successfully deleted"
    redirect_to listings_path
  end

  def favorite
    authorize @dress
    @dresses = policy_scope(Dress).order(created_at: :desc)
    authorize @dresses
    if current_user.favorited?(@dress)
      current_user.unfavorite(@dress)
    else
      current_user.favorite(@dress)
    end
    respond_to do |format|
      format.js
      format.html { render 'index.html', locals: { dresses: @dresses } }
      format.text { render 'index.html', locals: { dresses: @dresses } }
    end
  end

  def favorites
    @dresses = policy_scope(Dress).order(created_at: :desc)
    @fav_dresses = current_user.all_favorited
    authorize @dresses
    respond_to do |format|
      format.html
    end
  end

  def listings
    @dresses = policy_scope(Dress).order(created_at: :desc)
    @dresses = Dress.where('user_id = ?', current_user)
    authorize @dresses
  end

  private

  def dress_params
    params.require(:dress).permit(:brand, :color, :size, :style, :description,
                                  :price_per_day, :longitude, :latitude, photos: [])
  end

  def set_dress
    @dress = Dress.find(params[:id])
  end
end

app/views/dresses/_form.html.erb
<%= simple_form_for(@dress) do |f| %>
  <%= f.input :brand %>
  <%= f.input :color %>
  <%= f.input :size, as: :select, collection: 0..100 %>
  <%= f.input :style, as: :select, collection: %w[Princess Mermaid A-Line Ballgown Empire
                                        Column Hi-Lo Trumpet Asymmetrical Bateau Mini] %>
  <%= f.input :description %>
  <%= f.input :price_per_day, input_html: { min: '1'} %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit class: 'btn btn-outline-secondary' %>
<% end %>

app/views/dresses/_list.html.erb
<div data-refresh-list-target="list">
  <div class="row justify-content-center">
    <% dresses.each do |dress| %>
      <div class="dress-card text-center mb-3">
        <%= link_to dress_path(dress) do %>
          <%= render 'dresses/dress_images.html.erb', dress: dress %>
        <% end %>
        <span class="favorite">
          <% if user_signed_in? && dress.favorited_by?(current_user) %>
            <%= link_to "", favorite_path(dress), class: "fa fa-heart pink", id: "favorite-button-#{dress.id}", remote: true %>
          <% else %>
            <%= link_to "", favorite_path(dress), class: "fa fa-heart", id: "favorite-button-#{dress.id}", remote: true %>
          <% end %>
        </span>
        <p><%= dress.description.truncate(30, omission: " ...") %></p>
        <p><%= number_to_currency(dress.price_per_day, {unit: '¥', precision: 0}) %> per day</p>
      </div>
      <% end %>
    </div>
</div>

app/views/dresses/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-12">
      <h2 class="mt-5">Update Your Dress Info</h2>
      <%= render 'form', dress: @dress %>
    </div>
  </div>
</div>

app/views/dresses/favorite.js.erb
{
  const favoriteButton = document.querySelector('#favorite-button-<%= @dress.id %>');
  favoriteButton.classList.toggle('pink');
}

app/views/dresses/favorites.html.erb
<div class="container">
  <h3 class="my-3">Your Favorites</h3>
  <% if @fav_dresses.empty? %>
    <p class="mb-5">No favorites yet!</p>
  <% end %>
  <div class="row justify-content-center">
    <% @fav_dresses.each do |dress| %>
    <div class="dress-card text-center mb-3">
      <%= link_to dress_path(dress) do %>
        <%= render 'dresses/dress_images.html.erb', dress: dress %>
      <% end %>
      <span class="favorite">
      <% if current_user.favorited?(dress) %>
        <%= link_to "", favorite_path(dress), class: "fa fa-heart pink", id: "favorite-button-#{dress.id}", remote: true %>
      <% else %>
        <%= link_to "", favorite_path(dress), class: "fa fa-heart", id: "favorite-button-#{dress.id}", remote: true %>
      <% end %>
      </span>
      <p><%= dress.description.truncate(30, omission: " ...") %></p>
      <p><%= number_to_currency(dress.price_per_day, {unit: '¥', precision: 0}) %> per day</p>
    </div>
    <% end %>
  </div>
    <%= link_to 'Browse Dresses', dresses_path, class: 'btn btn-outline-secondary float-right' %>

</div>

app/views/dresses/index.html.erb
<div class="container">
  <h3 class="my-3">
    <% if @query == nil %>
    All Our Dresses
    <% elsif @dresses.count > 1 %>
      <%= @dresses.count %> dresses found for you
    <% elsif @dresses.count == 1 %>
      <%= @dresses.count %> dress found for you
    <% else %>
      Sorry, no results were found for "<%= @query %>."
    <% end %>
  </h3>

  <%= render 'list', dresses: @dresses %>

</div>

app/views/dresses/listings.html.erb
<div class="container">
  <h3 class="my-3">Your Listings</h3>
  <p class="mb-5">
    <% if @dresses.count == 0 %>
      No listings yet!
    <% end %>
  </p>
  <%# <% @dresses.count > 1 ? @dresses.count dresses :
     @dresses.count dress %>
  <div class="row justify-content-center">
    <% @dresses.each do |dress| %>
    <div class="dress-card text-center mb-3 listings">
      <%= link_to dress_path(dress) do %>
        <% if dress.photos.attached? %>
          <%= cl_image_tag(dress.photos.first.key) %>
        <% elsif dress.dress_url.present? %>
          <%= image_tag(dress.dress_url) %>
        <% else %>
          <%= image_tag("bridal_gown_silhouette.png") %>
        <% end %>
      <% end %>
      <p><%= dress.description.truncate(30, omission: " ...") %></p>
      <p><%= number_to_currency(dress.price_per_day, {unit: '¥', precision: 0}) %> per day</p>
      <div class="edit-dress">
        <%= link_to "", dress_path(dress), method: :delete, class: "hidden delete-link" %>
        <%= link_to "Edit", edit_dress_path(dress), class: "btn btn-outline-secondary mb-5 mx-1" %>
        <button class="sweet-alert-delete btn btn-outline-secondary mb-5 mx-1 float-right">Delete</button>
      </div>
    </div>
    <% end %>
  </div>
  <%= link_to 'Add a New Dress', new_dress_path, class: 'btn btn-outline-secondary float-right' %>
</div>

app/views/dresses/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-12">
      <h2 class="mt-4">Add a new dress</h2>
      <%= render 'form', dress: @dress %>
      <%= link_to 'Cancel', listings_path, class: 'btn btn-outline-secondary m-3 float-right' %>
    </div>
  </div>
</div>

app/views/dresses/show.html.erb
<div class="container">
  <%= render 'shared/carousel' %>
  <div class="m-3">
    <h3><%= @dress.style %> style dress designed by <%= @dress.brand %></h3>
    <p><%= @dress.description %></p>
    <p>Size: <%= @dress.size %></p>
    <button type="button" class="btn btn-dark float-right" data-toggle="modal" data-target="#bookingModal">
      Book Dress
    </button>
    <p>Color: <%= @dress.color %></p>
    <p>Price Per Day: <%= number_to_currency(@dress.price_per_day, {unit: '¥', precision: 0}) %></p>
  </div>
  <h3 class="m-3 my-5">This Dress's Reviews</h3>

  <div data-controller="insert-in-list" class="reviews mx-auto">
    <div id="reviews" data-insert-in-list-target="items">
      <% if @dress.reviews.blank? %>
        <p class="m-3" id=" first-review" data-insert-in-list-target="header">Be the first to leave a review for this dress!</p>
      <% else %>
        <% @dress.reviews.each do |review| %>
          <%= render review %>
        <% end %>
      <% end %>
    </div>

    <div class="m-3 my-5">
      <h3>Leave a Review</h3>
      <%= render 'reviews/form', dress: @dress, review: @review %>
    </div>
  </div>

  <%= link_to 'Back', :back, class: "btn btn-outline-secondary mb-5 m-3" %>
</div>

<!-- Modal -->
<div class="modal fade" id="bookingModal" tabindex="-1" role="dialog" aria-labelledby="bookingModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="bookingModalLabel">Book This Dress</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'bookings/form', dress: @dress, booking: @booking %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>